// prisma/seed-sporting-cp.ts
import { PrismaClient, PlayerPosition } from "@prisma/client";

const prisma = new PrismaClient();

const SPORTING_ID = "cmmx9irzm000whxghl1er4o41";

function slugify(value: string) {
  return value
    .normalize("NFKD")
    .replace(/[\u0300-\u036f]/g, "")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

async function main() {
  console.log("🌱 Seeding current Sporting CP first-team players...");

  const players = [
    // GOALKEEPERS
    {
      teamId: SPORTING_ID,
      externalId: null,
      name: "Rui Silva",
      shortName: "Rui Silva",
      slug: slugify("Rui Silva"),
      photo: null,
      position: PlayerPosition.GOALKEEPER,
      shirtNumber: 1,
      age: 32,
      dateOfBirth: new Date("1994-02-07"),
      nationality: "Portugal",
      countryOfBirth: "Portugal",
      heightCm: 191,
      weightKg: null,
      preferredFoot: "Right",
      isActive: true,
      isInjured: false,
      isSuspended: false,
      injuryNote: null,
      marketValue: 7000000,
      lastSyncedAt: new Date(),
    },
    {
      teamId: SPORTING_ID,
      externalId: null,
      name: "João Virgínia",
      shortName: "João Virgínia",
      slug: slugify("João Virgínia"),
      photo: null,
      position: PlayerPosition.GOALKEEPER,
      shirtNumber: 12,
      age: 26,
      dateOfBirth: new Date("1999-10-10"),
      nationality: "Portugal",
      countryOfBirth: "Portugal",
      heightCm: 192,
      weightKg: null,
      preferredFoot: "Right",
      isActive: true,
      isInjured: false,
      isSuspended: false,
      injuryNote: null,
      marketValue: 1000000,
      lastSyncedAt: new Date(),
    },
    {
      teamId: SPORTING_ID,
      externalId: null,
      name: "Diego Callai",
      shortName: "Diego Callai",
      slug: slugify("Diego Callai"),
      photo: null,
      position: PlayerPosition.GOALKEEPER,
      shirtNumber: 41,
      age: 21,
      dateOfBirth: new Date("2004-07-31"),
      nationality: "Brazil",
      countryOfBirth: "Brazil",
      heightCm: 194,
      weightKg: null,
      preferredFoot: "Right",
      isActive: true,
      isInjured: false,
      isSuspended: false,
      injuryNote: null,
      marketValue: null,
      lastSyncedAt: new Date(),
    },
    {
      teamId: SPORTING_ID,
      externalId: null,
      name: "Francisco Silva",
      shortName: "Francisco Silva",
      slug: slugify("Francisco Silva"),
      photo: null,
      position: PlayerPosition.GOALKEEPER,
      shirtNumber: 99,
      age: 19,
      dateOfBirth: new Date("2006-01-17"),
      nationality: "Portugal",
      countryOfBirth: "Portugal",
      heightCm: null,
      weightKg: null,
      preferredFoot: "Right",
      isActive: true,
      isInjured: false,
      isSuspended: false,
      injuryNote: null,
      marketValue: null,
      lastSyncedAt: new Date(),
    },

    // DEFENDERS
    {
      teamId: SPORTING_ID,
      externalId: null,
      name: "Zeno Debast",
      shortName: "Debast",
      slug: slugify("Zeno Debast"),
      photo: null,
      position: PlayerPosition.DEFENDER,
      shirtNumber: 6,
      age: 22,
      dateOfBirth: new Date("2003-10-24"),
      nationality: "Belgium",
      countryOfBirth: "Belgium",
      heightCm: 191,
      weightKg: null,
      preferredFoot: "Right",
      isActive: true,
      isInjured: false,
      isSuspended: false,
      injuryNote: null,
      marketValue: 30000000,
      lastSyncedAt: new Date(),
    },
    {
      teamId: SPORTING_ID,
      externalId: null,
      name: "Nuno Santos",
      shortName: "Nuno Santos",
      slug: slugify("Nuno Santos"),
      photo: null,
      position: PlayerPosition.DEFENDER,
      shirtNumber: 11,
      age: 31,
      dateOfBirth: new Date("1995-02-13"),
      nationality: "Portugal",
      countryOfBirth: "Portugal",
      heightCm: 177,
      weightKg: null,
      preferredFoot: "Left",
      isActive: true,
      isInjured: false,
      isSuspended: false,
      injuryNote: null,
      marketValue: 5000000,
      lastSyncedAt: new Date(),
    },
    {
      teamId: SPORTING_ID,
      externalId: null,
      name: "Georgios Vagiannidis",
      shortName: "Vagiannidis",
      slug: slugify("Georgios Vagiannidis"),
      photo: null,
      position: PlayerPosition.DEFENDER,
      shirtNumber: 13,
      age: 24,
      dateOfBirth: new Date("2001-09-12"),
      nationality: "Greece",
      countryOfBirth: "Greece",
      heightCm: 182,
      weightKg: null,
      preferredFoot: "Right",
      isActive: true,
      isInjured: false,
      isSuspended: false,
      injuryNote: null,
      marketValue: 11000000,
      lastSyncedAt: new Date(),
    },
    {
      teamId: SPORTING_ID,
      externalId: null,
      name: "Maxi Araújo",
      shortName: "Maxi Araújo",
      slug: slugify("Maxi Araújo"),
      photo: null,
      position: PlayerPosition.DEFENDER,
      shirtNumber: 20,
      age: 26,
      dateOfBirth: new Date("2000-02-15"),
      nationality: "Uruguay",
      countryOfBirth: "Uruguay",
      heightCm: 179,
      weightKg: null,
      preferredFoot: "Left",
      isActive: true,
      isInjured: false,
      isSuspended: false,
      injuryNote: null,
      marketValue: 25000000,
      lastSyncedAt: new Date(),
    },
    {
      teamId: SPORTING_ID,
      externalId: null,
      name: "Iván Fresneda",
      shortName: "Fresneda",
      slug: slugify("Iván Fresneda"),
      photo: null,
      position: PlayerPosition.DEFENDER,
      shirtNumber: 22,
      age: 21,
      dateOfBirth: new Date("2004-09-28"),
      nationality: "Spain",
      countryOfBirth: "Spain",
      heightCm: 182,
      weightKg: null,
      preferredFoot: "Right",
      isActive: true,
      isInjured: false,
      isSuspended: false,
      injuryNote: null,
      marketValue: 12000000,
      lastSyncedAt: new Date(),
    },
    {
      teamId: SPORTING_ID,
      externalId: null,
      name: "Gonçalo Inácio",
      shortName: "Gonçalo Inácio",
      slug: slugify("Gonçalo Inácio"),
      photo: null,
      position: PlayerPosition.DEFENDER,
      shirtNumber: 25,
      age: 24,
      dateOfBirth: new Date("2001-08-25"),
      nationality: "Portugal",
      countryOfBirth: "Portugal",
      heightCm: 186,
      weightKg: null,
      preferredFoot: "Left",
      isActive: true,
      isInjured: false,
      isSuspended: false,
      injuryNote: null,
      marketValue: 40000000,
      lastSyncedAt: new Date(),
    },
    {
      teamId: SPORTING_ID,
      externalId: null,
      name: "Ousmane Diomande",
      shortName: "Diomande",
      slug: slugify("Ousmane Diomande"),
      photo: null,
      position: PlayerPosition.DEFENDER,
      shirtNumber: 26,
      age: 22,
      dateOfBirth: new Date("2003-12-04"),
      nationality: "Cote d'Ivoire",
      countryOfBirth: "Cote d'Ivoire",
      heightCm: 190,
      weightKg: null,
      preferredFoot: "Right",
      isActive: true,
      isInjured: false,
      isSuspended: false,
      injuryNote: null,
      marketValue: 45000000,
      lastSyncedAt: new Date(),
    },
    {
      teamId: SPORTING_ID,
      externalId: null,
      name: "Eduardo Quaresma",
      shortName: "Eduardo Quaresma",
      slug: slugify("Eduardo Quaresma"),
      photo: null,
      position: PlayerPosition.DEFENDER,
      shirtNumber: 72,
      age: 24,
      dateOfBirth: new Date("2002-03-02"),
      nationality: "Portugal",
      countryOfBirth: "Portugal",
      heightCm: 185,
      weightKg: null,
      preferredFoot: "Right",
      isActive: true,
      isInjured: false,
      isSuspended: false,
      injuryNote: null,
      marketValue: 15000000,
      lastSyncedAt: new Date(),
    },
    {
      teamId: SPORTING_ID,
      externalId: null,
      name: "Ricardo Mangas",
      shortName: "Mangas",
      slug: slugify("Ricardo Mangas"),
      photo: null,
      position: PlayerPosition.DEFENDER,
      shirtNumber: 91,
      age: 28,
      dateOfBirth: new Date("1998-03-08"),
      nationality: "Portugal",
      countryOfBirth: "Portugal",
      heightCm: 183,
      weightKg: null,
      preferredFoot: "Left",
      isActive: true,
      isInjured: false,
      isSuspended: false,
      injuryNote: null,
      marketValue: 2500000,
      lastSyncedAt: new Date(),
    },

    // MIDFIELDERS
    {
      teamId: SPORTING_ID,
      externalId: null,
      name: "Hidemasa Morita",
      shortName: "Morita",
      slug: slugify("Hidemasa Morita"),
      photo: null,
      position: PlayerPosition.MIDFIELDER,
      shirtNumber: 5,
      age: 30,
      dateOfBirth: new Date("1995-05-10"),
      nationality: "Japan",
      countryOfBirth: "Japan",
      heightCm: 177,
      weightKg: null,
      preferredFoot: "Right",
      isActive: true,
      isInjured: false,
      isSuspended: false,
      injuryNote: null,
      marketValue: 9000000,
      lastSyncedAt: new Date(),
    },
    {
      teamId: SPORTING_ID,
      externalId: null,
      name: "Pedro Gonçalves",
      shortName: "Pedro Gonçalves",
      slug: slugify("Pedro Gonçalves"),
      photo: null,
      position: PlayerPosition.MIDFIELDER,
      shirtNumber: 8,
      age: 27,
      dateOfBirth: new Date("1998-06-28"),
      nationality: "Portugal",
      countryOfBirth: "Portugal",
      heightCm: 173,
      weightKg: null,
      preferredFoot: "Right",
      isActive: true,
      isInjured: false,
      isSuspended: false,
      injuryNote: null,
      marketValue: 28000000,
      lastSyncedAt: new Date(),
    },
    {
      teamId: SPORTING_ID,
      externalId: null,
      name: "Giorgi Kochorashvili",
      shortName: "Kochorashvili",
      slug: slugify("Giorgi Kochorashvili"),
      photo: null,
      position: PlayerPosition.MIDFIELDER,
      shirtNumber: 14,
      age: 26,
      dateOfBirth: new Date("1999-06-29"),
      nationality: "Georgia",
      countryOfBirth: "Georgia",
      heightCm: 178,
      weightKg: null,
      preferredFoot: "Right",
      isActive: true,
      isInjured: false,
      isSuspended: false,
      injuryNote: null,
      marketValue: 5000000,
      lastSyncedAt: new Date(),
    },
    {
      teamId: SPORTING_ID,
      externalId: null,
      name: "Daniel Bragança",
      shortName: "Bragança",
      slug: slugify("Daniel Bragança"),
      photo: null,
      position: PlayerPosition.MIDFIELDER,
      shirtNumber: 23,
      age: 26,
      dateOfBirth: new Date("2000-05-27"),
      nationality: "Portugal",
      countryOfBirth: "Portugal",
      heightCm: 167,
      weightKg: null,
      preferredFoot: "Right",
      isActive: true,
      isInjured: false,
      isSuspended: false,
      injuryNote: null,
      marketValue: 10000000,
      lastSyncedAt: new Date(),
    },
    {
      teamId: SPORTING_ID,
      externalId: null,
      name: "Morten Hjulmand",
      shortName: "Hjulmand",
      slug: slugify("Morten Hjulmand"),
      photo: null,
      position: PlayerPosition.MIDFIELDER,
      shirtNumber: 42,
      age: 26,
      dateOfBirth: new Date("1999-06-25"),
      nationality: "Denmark",
      countryOfBirth: "Denmark",
      heightCm: 185,
      weightKg: null,
      preferredFoot: "Right",
      isActive: true,
      isInjured: false,
      isSuspended: false,
      injuryNote: null,
      marketValue: 45000000,
      lastSyncedAt: new Date(),
    },
    {
      teamId: SPORTING_ID,
      externalId: null,
      name: "João Simões",
      shortName: "João Simões",
      slug: slugify("João Simões"),
      photo: null,
      position: PlayerPosition.MIDFIELDER,
      shirtNumber: 52,
      age: 19,
      dateOfBirth: new Date("2006-09-02"),
      nationality: "Portugal",
      countryOfBirth: "Portugal",
      heightCm: 180,
      weightKg: null,
      preferredFoot: "Right",
      isActive: true,
      isInjured: false,
      isSuspended: false,
      injuryNote: null,
      marketValue: 15000000,
      lastSyncedAt: new Date(),
    },

    // FORWARDS
    {
      teamId: SPORTING_ID,
      externalId: null,
      name: "Geovany Quenda",
      shortName: "Quenda",
      slug: slugify("Geovany Quenda"),
      photo: null,
      position: PlayerPosition.FORWARD,
      shirtNumber: 7,
      age: 18,
      dateOfBirth: new Date("2007-04-30"),
      nationality: "Portugal",
      countryOfBirth: "Guinea-Bissau",
      heightCm: 172,
      weightKg: null,
      preferredFoot: "Left",
      isActive: true,
      isInjured: false,
      isSuspended: false,
      injuryNote: null,
      marketValue: 42000000,
      lastSyncedAt: new Date(),
    },
    {
      teamId: SPORTING_ID,
      externalId: null,
      name: "Geny Catamo",
      shortName: "Geny Catamo",
      slug: slugify("Geny Catamo"),
      photo: null,
      position: PlayerPosition.FORWARD,
      shirtNumber: 10,
      age: 25,
      dateOfBirth: new Date("2001-01-26"),
      nationality: "Mozambique",
      countryOfBirth: "Mozambique",
      heightCm: 172,
      weightKg: null,
      preferredFoot: "Left",
      isActive: true,
      isInjured: false,
      isSuspended: false,
      injuryNote: null,
      marketValue: 20000000,
      lastSyncedAt: new Date(),
    },
    {
      teamId: SPORTING_ID,
      externalId: null,
      name: "Souleymane Faye",
      shortName: "Faye",
      slug: slugify("Souleymane Faye"),
      photo: null,
      position: PlayerPosition.FORWARD,
      shirtNumber: 15,
      age: 23,
      dateOfBirth: new Date("2002-02-14"),
      nationality: "Senegal",
      countryOfBirth: "Senegal",
      heightCm: 178,
      weightKg: null,
      preferredFoot: "Right",
      isActive: true,
      isInjured: false,
      isSuspended: false,
      injuryNote: null,
      marketValue: 4000000,
      lastSyncedAt: new Date(),
    },
    {
      teamId: SPORTING_ID,
      externalId: null,
      name: "Francisco Trincão",
      shortName: "Trincão",
      slug: slugify("Francisco Trincão"),
      photo: null,
      position: PlayerPosition.FORWARD,
      shirtNumber: 17,
      age: 26,
      dateOfBirth: new Date("1999-12-29"),
      nationality: "Portugal",
      countryOfBirth: "Portugal",
      heightCm: 184,
      weightKg: null,
      preferredFoot: "Left",
      isActive: true,
      isInjured: false,
      isSuspended: false,
      injuryNote: null,
      marketValue: 35000000,
      lastSyncedAt: new Date(),
    },
    {
      teamId: SPORTING_ID,
      externalId: null,
      name: "Luís Guilherme",
      shortName: "Luís Guilherme",
      slug: slugify("Luís Guilherme"),
      photo: null,
      position: PlayerPosition.FORWARD,
      shirtNumber: 31,
      age: 20,
      dateOfBirth: new Date("2006-02-09"),
      nationality: "Brazil",
      countryOfBirth: "Brazil",
      heightCm: 175,
      weightKg: null,
      preferredFoot: "Left",
      isActive: true,
      isInjured: false,
      isSuspended: false,
      injuryNote: null,
      marketValue: 12000000,
      lastSyncedAt: new Date(),
    },
    {
      teamId: SPORTING_ID,
      externalId: null,
      name: "Fotis Ioannidis",
      shortName: "Ioannidis",
      slug: slugify("Fotis Ioannidis"),
      photo: null,
      position: PlayerPosition.FORWARD,
      shirtNumber: 89,
      age: 26,
      dateOfBirth: new Date("2000-01-10"),
      nationality: "Greece",
      countryOfBirth: "Greece",
      heightCm: 187,
      weightKg: null,
      preferredFoot: "Right",
      isActive: true,
      isInjured: false,
      isSuspended: false,
      injuryNote: null,
      marketValue: 18000000,
      lastSyncedAt: new Date(),
    },
    {
      teamId: SPORTING_ID,
      externalId: null,
      name: "Luis Suárez",
      shortName: "Luis Suárez",
      slug: slugify("Luis Suárez"),
      photo: null,
      position: PlayerPosition.FORWARD,
      shirtNumber: 97,
      age: 28,
      dateOfBirth: new Date("1998-12-02"),
      nationality: "Colombia",
      countryOfBirth: "Colombia",
      heightCm: 185,
      weightKg: null,
      preferredFoot: "Right",
      isActive: true,
      isInjured: false,
      isSuspended: false,
      injuryNote: null,
      marketValue: 28000000,
      lastSyncedAt: new Date(),
    },
  ];

  for (const player of players) {
    await prisma.player.upsert({
      where: {
        teamId_name: {
          teamId: player.teamId,
          name: player.name,
        },
      },
      update: player,
      create: player,
    });
  }

  console.log(`✅ Sporting CP players seeded: ${players.length}`);
}

main()
  .catch((error) => {
    console.error("❌ Error seeding Sporting CP players:", error);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });