// prisma/seed-atletico-madrid.ts
import { PrismaClient, PlayerPosition } from "@prisma/client";

const prisma = new PrismaClient();

const ATLETICO_ID = "cmmx9ir1t000ahxghypdyfzra";

function slugify(value: string) {
  return value
    .normalize("NFKD")
    .replace(/[\u0300-\u036f]/g, "")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

async function main() {
  console.log("🌱 Seeding Atlético Madrid players...");

  const players = [
    // GOALKEEPERS
    {
      teamId: ATLETICO_ID,
      externalId: null,
      name: "Juan Musso",
      shortName: "Musso",
      slug: slugify("Juan Musso"),
      photo: null,
      position: PlayerPosition.GOALKEEPER,
      shirtNumber: 1,
      age: 31,
      dateOfBirth: null,
      nationality: "Argentina",
      countryOfBirth: null,
      heightCm: 191,
      weightKg: null,
      preferredFoot: "right",
      isActive: true,
      isInjured: false,
      isSuspended: false,
      injuryNote: null,
      marketValue: 3000000,
      lastSyncedAt: new Date(),
    },
    {
      teamId: ATLETICO_ID,
      externalId: null,
      name: "Jan Oblak",
      shortName: "Oblak",
      slug: slugify("Jan Oblak"),
      photo: null,
      position: PlayerPosition.GOALKEEPER,
      shirtNumber: 13,
      age: 33,
      dateOfBirth: null,
      nationality: "Slovenia",
      countryOfBirth: null,
      heightCm: 188,
      weightKg: null,
      preferredFoot: "right",
      isActive: true,
      isInjured: false,
      isSuspended: false,
      injuryNote: null,
      marketValue: 22000000,
      lastSyncedAt: new Date(),
    },
    {
      teamId: ATLETICO_ID,
      externalId: null,
      name: "Salvi Esquivel",
      shortName: "Esquivel",
      slug: slugify("Salvi Esquivel"),
      photo: null,
      position: PlayerPosition.GOALKEEPER,
      shirtNumber: 31,
      age: 20,
      dateOfBirth: null,
      nationality: "Spain",
      countryOfBirth: null,
      heightCm: 191,
      weightKg: null,
      preferredFoot: "right",
      isActive: true,
      isInjured: false,
      isSuspended: false,
      injuryNote: null,
      marketValue: 200000,
      lastSyncedAt: new Date(),
    },
    {
      teamId: ATLETICO_ID,
      externalId: null,
      name: "Mario de Luis",
      shortName: "Mario de Luis",
      slug: slugify("Mario de Luis"),
      photo: null,
      position: PlayerPosition.GOALKEEPER,
      shirtNumber: 33,
      age: 23,
      dateOfBirth: null,
      nationality: "Spain",
      countryOfBirth: null,
      heightCm: 185,
      weightKg: null,
      preferredFoot: "right",
      isActive: true,
      isInjured: false,
      isSuspended: false,
      injuryNote: null,
      marketValue: 300000,
      lastSyncedAt: new Date(),
    },

    // DEFENDERS
    {
      teamId: ATLETICO_ID,
      externalId: null,
      name: "José María Giménez",
      shortName: "Giménez",
      slug: slugify("José María Giménez"),
      photo: null,
      position: PlayerPosition.DEFENDER,
      shirtNumber: 2,
      age: 31,
      dateOfBirth: null,
      nationality: "Uruguay",
      countryOfBirth: null,
      heightCm: 185,
      weightKg: null,
      preferredFoot: "right",
      isActive: true,
      isInjured: false,
      isSuspended: false,
      injuryNote: null,
      marketValue: 12000000,
      lastSyncedAt: new Date(),
    },
    {
      teamId: ATLETICO_ID,
      externalId: null,
      name: "Matteo Ruggeri",
      shortName: "Ruggeri",
      slug: slugify("Matteo Ruggeri"),
      photo: null,
      position: PlayerPosition.DEFENDER,
      shirtNumber: 3,
      age: 23,
      dateOfBirth: null,
      nationality: "Italy",
      countryOfBirth: null,
      heightCm: 187,
      weightKg: null,
      preferredFoot: "left",
      isActive: true,
      isInjured: false,
      isSuspended: false,
      injuryNote: null,
      marketValue: 17000000,
      lastSyncedAt: new Date(),
    },
    {
      teamId: ATLETICO_ID,
      externalId: null,
      name: "Clément Lenglet",
      shortName: "Lenglet",
      slug: slugify("Clément Lenglet"),
      photo: null,
      position: PlayerPosition.DEFENDER,
      shirtNumber: 15,
      age: 30,
      dateOfBirth: null,
      nationality: "France",
      countryOfBirth: null,
      heightCm: 186,
      weightKg: null,
      preferredFoot: "left",
      isActive: true,
      isInjured: false,
      isSuspended: false,
      injuryNote: null,
      marketValue: 8000000,
      lastSyncedAt: new Date(),
    },
    {
      teamId: ATLETICO_ID,
      externalId: null,
      name: "Nahuel Molina",
      shortName: "Molina",
      slug: slugify("Nahuel Molina"),
      photo: null,
      position: PlayerPosition.DEFENDER,
      shirtNumber: 16,
      age: 28,
      dateOfBirth: null,
      nationality: "Argentina",
      countryOfBirth: null,
      heightCm: 179,
      weightKg: null,
      preferredFoot: "right",
      isActive: true,
      isInjured: false,
      isSuspended: false,
      injuryNote: null,
      marketValue: 15000000,
      lastSyncedAt: new Date(),
    },
    {
      teamId: ATLETICO_ID,
      externalId: null,
      name: "Dávid Hancko",
      shortName: "Hancko",
      slug: slugify("Dávid Hancko"),
      photo: null,
      position: PlayerPosition.DEFENDER,
      shirtNumber: 17,
      age: 28,
      dateOfBirth: null,
      nationality: "Slovakia",
      countryOfBirth: null,
      heightCm: 188,
      weightKg: null,
      preferredFoot: "left",
      isActive: true,
      isInjured: false,
      isSuspended: false,
      injuryNote: null,
      marketValue: 26000000,
      lastSyncedAt: new Date(),
    },
    {
      teamId: ATLETICO_ID,
      externalId: null,
      name: "Marc Pubill",
      shortName: "Pubill",
      slug: slugify("Marc Pubill"),
      photo: null,
      position: PlayerPosition.DEFENDER,
      shirtNumber: 18,
      age: 22,
      dateOfBirth: null,
      nationality: "Spain",
      countryOfBirth: null,
      heightCm: 190,
      weightKg: null,
      preferredFoot: "right",
      isActive: true,
      isInjured: false,
      isSuspended: false,
      injuryNote: null,
      marketValue: 16000000,
      lastSyncedAt: new Date(),
    },
    {
      teamId: ATLETICO_ID,
      externalId: null,
      name: "Robin Le Normand",
      shortName: "Le Normand",
      slug: slugify("Robin Le Normand"),
      photo: null,
      position: PlayerPosition.DEFENDER,
      shirtNumber: 24,
      age: 29,
      dateOfBirth: null,
      nationality: "Spain",
      countryOfBirth: null,
      heightCm: 188,
      weightKg: null,
      preferredFoot: "right",
      isActive: true,
      isInjured: false,
      isSuspended: false,
      injuryNote: null,
      marketValue: 40000000,
      lastSyncedAt: new Date(),
    },
    {
      teamId: ATLETICO_ID,
      externalId: null,
      name: "Ilias Kostis",
      shortName: "Kostis",
      slug: slugify("Ilias Kostis"),
      photo: null,
      position: PlayerPosition.DEFENDER,
      shirtNumber: 26,
      age: 23,
      dateOfBirth: null,
      nationality: "Greece",
      countryOfBirth: null,
      heightCm: 193,
      weightKg: null,
      preferredFoot: "left",
      isActive: true,
      isInjured: false,
      isSuspended: false,
      injuryNote: null,
      marketValue: 800000,
      lastSyncedAt: new Date(),
    },
    {
      teamId: ATLETICO_ID,
      externalId: null,
      name: "Daniel Martinez",
      shortName: "Daniel Martinez",
      slug: slugify("Daniel Martinez"),
      photo: null,
      position: PlayerPosition.DEFENDER,
      shirtNumber: 30,
      age: 21,
      dateOfBirth: null,
      nationality: "Spain",
      countryOfBirth: null,
      heightCm: 185,
      weightKg: null,
      preferredFoot: "right",
      isActive: true,
      isInjured: false,
      isSuspended: false,
      injuryNote: null,
      marketValue: 300000,
      lastSyncedAt: new Date(),
    },
    {
      teamId: ATLETICO_ID,
      externalId: null,
      name: "Javier Boñar",
      shortName: "Boñar",
      slug: slugify("Javier Boñar"),
      photo: null,
      position: PlayerPosition.DEFENDER,
      shirtNumber: 32,
      age: 20,
      dateOfBirth: null,
      nationality: "Spain",
      countryOfBirth: null,
      heightCm: 178,
      weightKg: null,
      preferredFoot: "right",
      isActive: true,
      isInjured: false,
      isSuspended: false,
      injuryNote: null,
      marketValue: 400000,
      lastSyncedAt: new Date(),
    },
    {
      teamId: ATLETICO_ID,
      externalId: null,
      name: "Gerónimo Spina",
      shortName: "Spina",
      slug: slugify("Gerónimo Spina"),
      photo: null,
      position: PlayerPosition.DEFENDER,
      shirtNumber: 36,
      age: 21,
      dateOfBirth: null,
      nationality: "Argentina",
      countryOfBirth: null,
      heightCm: 188,
      weightKg: null,
      preferredFoot: "right",
      isActive: true,
      isInjured: false,
      isSuspended: false,
      injuryNote: null,
      marketValue: 300000,
      lastSyncedAt: new Date(),
    },
    {
      teamId: ATLETICO_ID,
      externalId: null,
      name: "Aleksa Puric",
      shortName: "Puric",
      slug: slugify("Aleksa Puric"),
      photo: null,
      position: PlayerPosition.DEFENDER,
      shirtNumber: 40,
      age: 22,
      dateOfBirth: null,
      nationality: "Serbia",
      countryOfBirth: null,
      heightCm: 185,
      weightKg: null,
      preferredFoot: "right",
      isActive: true,
      isInjured: false,
      isSuspended: false,
      injuryNote: null,
      marketValue: 200000,
      lastSyncedAt: new Date(),
    },

    // MIDFIELDERS
    {
      teamId: ATLETICO_ID,
      externalId: null,
      name: "Rodrigo Mendoza",
      shortName: "Rodrigo Mendoza",
      slug: slugify("Rodrigo Mendoza"),
      photo: null,
      position: PlayerPosition.MIDFIELDER,
      shirtNumber: 4,
      age: 21,
      dateOfBirth: null,
      nationality: "Spain",
      countryOfBirth: null,
      heightCm: 183,
      weightKg: null,
      preferredFoot: "right",
      isActive: true,
      isInjured: false,
      isSuspended: false,
      injuryNote: null,
      marketValue: 500000,
      lastSyncedAt: new Date(),
    },
    {
      teamId: ATLETICO_ID,
      externalId: null,
      name: "Johnny Cardoso",
      shortName: "Johnny Cardoso",
      slug: slugify("Johnny Cardoso"),
      photo: null,
      position: PlayerPosition.MIDFIELDER,
      shirtNumber: 5,
      age: 24,
      dateOfBirth: null,
      nationality: "USA",
      countryOfBirth: null,
      heightCm: 185,
      weightKg: null,
      preferredFoot: "right",
      isActive: true,
      isInjured: false,
      isSuspended: false,
      injuryNote: null,
      marketValue: 24000000,
      lastSyncedAt: new Date(),
    },
    {
      teamId: ATLETICO_ID,
      externalId: null,
      name: "Koke",
      shortName: "Koke",
      slug: slugify("Koke"),
      photo: null,
      position: PlayerPosition.MIDFIELDER,
      shirtNumber: 6,
      age: 34,
      dateOfBirth: null,
      nationality: "Spain",
      countryOfBirth: null,
      heightCm: 176,
      weightKg: null,
      preferredFoot: "right",
      isActive: true,
      isInjured: false,
      isSuspended: false,
      injuryNote: null,
      marketValue: 3000000,
      lastSyncedAt: new Date(),
    },
    {
      teamId: ATLETICO_ID,
      externalId: null,
      name: "Pablo Barrios",
      shortName: "Barrios",
      slug: slugify("Pablo Barrios"),
      photo: null,
      position: PlayerPosition.MIDFIELDER,
      shirtNumber: 8,
      age: 22,
      dateOfBirth: null,
      nationality: "Spain",
      countryOfBirth: null,
      heightCm: 183,
      weightKg: null,
      preferredFoot: "right",
      isActive: true,
      isInjured: false,
      isSuspended: false,
      injuryNote: null,
      marketValue: 50000000,
      lastSyncedAt: new Date(),
    },
    {
      teamId: ATLETICO_ID,
      externalId: null,
      name: "Álex Baena",
      shortName: "Baena",
      slug: slugify("Álex Baena"),
      photo: null,
      position: PlayerPosition.MIDFIELDER,
      shirtNumber: 10,
      age: 24,
      dateOfBirth: null,
      nationality: "Spain",
      countryOfBirth: null,
      heightCm: 174,
      weightKg: null,
      preferredFoot: "left",
      isActive: true,
      isInjured: false,
      isSuspended: false,
      injuryNote: null,
      marketValue: 42000000,
      lastSyncedAt: new Date(),
    },
    {
      teamId: ATLETICO_ID,
      externalId: null,
      name: "Thiago Almada",
      shortName: "Thiago Almada",
      slug: slugify("Thiago Almada"),
      photo: null,
      position: PlayerPosition.MIDFIELDER,
      shirtNumber: 11,
      age: 24,
      dateOfBirth: null,
      nationality: "Argentina",
      countryOfBirth: null,
      heightCm: 171,
      weightKg: null,
      preferredFoot: "right",
      isActive: true,
      isInjured: false,
      isSuspended: false,
      injuryNote: null,
      marketValue: 21000000,
      lastSyncedAt: new Date(),
    },
    {
      teamId: ATLETICO_ID,
      externalId: null,
      name: "Marcos Llorente",
      shortName: "Llorente",
      slug: slugify("Marcos Llorente"),
      photo: null,
      position: PlayerPosition.MIDFIELDER,
      shirtNumber: 14,
      age: 31,
      dateOfBirth: null,
      nationality: "Spain",
      countryOfBirth: null,
      heightCm: 184,
      weightKg: null,
      preferredFoot: "right",
      isActive: true,
      isInjured: false,
      isSuspended: false,
      injuryNote: null,
      marketValue: 18000000,
      lastSyncedAt: new Date(),
    },
    {
      teamId: ATLETICO_ID,
      externalId: null,
      name: "Obed Vargas",
      shortName: "Obed Vargas",
      slug: slugify("Obed Vargas"),
      photo: null,
      position: PlayerPosition.MIDFIELDER,
      shirtNumber: 21,
      age: 20,
      dateOfBirth: null,
      nationality: "Mexico",
      countryOfBirth: null,
      heightCm: 175,
      weightKg: null,
      preferredFoot: "right",
      isActive: true,
      isInjured: false,
      isSuspended: false,
      injuryNote: null,
      marketValue: 8000000,
      lastSyncedAt: new Date(),
    },
    {
      teamId: ATLETICO_ID,
      externalId: null,
      name: "Jano Monserrate",
      shortName: "Jano Monserrate",
      slug: slugify("Jano Monserrate"),
      photo: null,
      position: PlayerPosition.MIDFIELDER,
      shirtNumber: 27,
      age: 20,
      dateOfBirth: null,
      nationality: "Spain",
      countryOfBirth: null,
      heightCm: 178,
      weightKg: null,
      preferredFoot: "right",
      isActive: true,
      isInjured: false,
      isSuspended: false,
      injuryNote: null,
      marketValue: 300000,
      lastSyncedAt: new Date(),
    },
    {
      teamId: ATLETICO_ID,
      externalId: null,
      name: "Taufik Seidu",
      shortName: "Taufik Seidu",
      slug: slugify("Taufik Seidu"),
      photo: null,
      position: PlayerPosition.MIDFIELDER,
      shirtNumber: 28,
      age: 18,
      dateOfBirth: null,
      nationality: "Spain",
      countryOfBirth: null,
      heightCm: 183,
      weightKg: null,
      preferredFoot: "right",
      isActive: true,
      isInjured: false,
      isSuspended: false,
      injuryNote: null,
      marketValue: 200000,
      lastSyncedAt: new Date(),
    },
    {
      teamId: ATLETICO_ID,
      externalId: null,
      name: "Julio Díaz",
      shortName: "Julio Díaz",
      slug: slugify("Julio Díaz"),
      photo: null,
      position: PlayerPosition.MIDFIELDER,
      shirtNumber: 34,
      age: 21,
      dateOfBirth: null,
      nationality: "Spain",
      countryOfBirth: null,
      heightCm: 170,
      weightKg: null,
      preferredFoot: "right",
      isActive: true,
      isInjured: false,
      isSuspended: false,
      injuryNote: null,
      marketValue: 200000,
      lastSyncedAt: new Date(),
    },
    {
      teamId: ATLETICO_ID,
      externalId: null,
      name: "Javier Serrano",
      shortName: "Javier Serrano",
      slug: slugify("Javier Serrano"),
      photo: null,
      position: PlayerPosition.MIDFIELDER,
      shirtNumber: 42,
      age: 23,
      dateOfBirth: null,
      nationality: "Spain",
      countryOfBirth: null,
      heightCm: 178,
      weightKg: null,
      preferredFoot: "right",
      isActive: true,
      isInjured: false,
      isSuspended: false,
      injuryNote: null,
      marketValue: 1000000,
      lastSyncedAt: new Date(),
    },
    {
      teamId: ATLETICO_ID,
      externalId: null,
      name: "Javier Morcillo",
      shortName: "Javier Morcillo",
      slug: slugify("Javier Morcillo"),
      photo: null,
      position: PlayerPosition.MIDFIELDER,
      shirtNumber: 47,
      age: 20,
      dateOfBirth: null,
      nationality: "Spain",
      countryOfBirth: null,
      heightCm: 183,
      weightKg: null,
      preferredFoot: "right",
      isActive: true,
      isInjured: false,
      isSuspended: false,
      injuryNote: null,
      marketValue: 200000,
      lastSyncedAt: new Date(),
    },

    // FORWARDS
    {
      teamId: ATLETICO_ID,
      externalId: null,
      name: "Antoine Griezmann",
      shortName: "Griezmann",
      slug: slugify("Antoine Griezmann"),
      photo: null,
      position: PlayerPosition.FORWARD,
      shirtNumber: 7,
      age: 35,
      dateOfBirth: null,
      nationality: "France",
      countryOfBirth: null,
      heightCm: 176,
      weightKg: null,
      preferredFoot: "left",
      isActive: true,
      isInjured: false,
      isSuspended: false,
      injuryNote: null,
      marketValue: 8000000,
      lastSyncedAt: new Date(),
    },
    {
      teamId: ATLETICO_ID,
      externalId: null,
      name: "Alexander Sørloth",
      shortName: "Sørloth",
      slug: slugify("Alexander Sørloth"),
      photo: null,
      position: PlayerPosition.FORWARD,
      shirtNumber: 9,
      age: 30,
      dateOfBirth: null,
      nationality: "Norway",
      countryOfBirth: null,
      heightCm: 195,
      weightKg: null,
      preferredFoot: "left",
      isActive: true,
      isInjured: false,
      isSuspended: false,
      injuryNote: null,
      marketValue: 25000000,
      lastSyncedAt: new Date(),
    },
    {
      teamId: ATLETICO_ID,
      externalId: null,
      name: "Julián Álvarez",
      shortName: "Julián Álvarez",
      slug: slugify("Julián Álvarez"),
      photo: null,
      position: PlayerPosition.FORWARD,
      shirtNumber: 19,
      age: 26,
      dateOfBirth: null,
      nationality: "Argentina",
      countryOfBirth: null,
      heightCm: 170,
      weightKg: null,
      preferredFoot: "right",
      isActive: true,
      isInjured: false,
      isSuspended: false,
      injuryNote: null,
      marketValue: 110000000,
      lastSyncedAt: new Date(),
    },
    {
      teamId: ATLETICO_ID,
      externalId: null,
      name: "Giuliano Simeone",
      shortName: "Giuliano Simeone",
      slug: slugify("Giuliano Simeone"),
      photo: null,
      position: PlayerPosition.FORWARD,
      shirtNumber: 20,
      age: 23,
      dateOfBirth: null,
      nationality: "Argentina",
      countryOfBirth: null,
      heightCm: 175,
      weightKg: null,
      preferredFoot: "right",
      isActive: true,
      isInjured: false,
      isSuspended: false,
      injuryNote: null,
      marketValue: 35000000,
      lastSyncedAt: new Date(),
    },
    {
      teamId: ATLETICO_ID,
      externalId: null,
      name: "Ademola Lookman",
      shortName: "Lookman",
      slug: slugify("Ademola Lookman"),
      photo: null,
      position: PlayerPosition.FORWARD,
      shirtNumber: 22,
      age: 28,
      dateOfBirth: null,
      nationality: "Nigeria",
      countryOfBirth: null,
      heightCm: 174,
      weightKg: null,
      preferredFoot: "right",
      isActive: true,
      isInjured: false,
      isSuspended: false,
      injuryNote: null,
      marketValue: 35000000,
      lastSyncedAt: new Date(),
    },
    {
      teamId: ATLETICO_ID,
      externalId: null,
      name: "Nicolás González",
      shortName: "Nicolás González",
      slug: slugify("Nicolás González"),
      photo: null,
      position: PlayerPosition.FORWARD,
      shirtNumber: 23,
      age: 28,
      dateOfBirth: null,
      nationality: "Argentina",
      countryOfBirth: null,
      heightCm: 180,
      weightKg: null,
      preferredFoot: "left",
      isActive: true,
      isInjured: false,
      isSuspended: false,
      injuryNote: null,
      marketValue: 28000000,
      lastSyncedAt: new Date(),
    },
    {
      teamId: ATLETICO_ID,
      externalId: null,
      name: "Rayane Belaid",
      shortName: "Rayane Belaid",
      slug: slugify("Rayane Belaid"),
      photo: null,
      position: PlayerPosition.FORWARD,
      shirtNumber: 29,
      age: 21,
      dateOfBirth: null,
      nationality: "Spain",
      countryOfBirth: null,
      heightCm: 173,
      weightKg: null,
      preferredFoot: "right",
      isActive: true,
      isInjured: false,
      isSuspended: false,
      injuryNote: null,
      marketValue: 200000,
      lastSyncedAt: new Date(),
    },
    {
      teamId: ATLETICO_ID,
      externalId: null,
      name: "Iker Luque",
      shortName: "Iker Luque",
      slug: slugify("Iker Luque"),
      photo: null,
      position: PlayerPosition.FORWARD,
      shirtNumber: 37,
      age: 20,
      dateOfBirth: null,
      nationality: "Spain",
      countryOfBirth: null,
      heightCm: 168,
      weightKg: null,
      preferredFoot: "right",
      isActive: true,
      isInjured: false,
      isSuspended: false,
      injuryNote: null,
      marketValue: 100000,
      lastSyncedAt: new Date(),
    },
    {
      teamId: ATLETICO_ID,
      externalId: null,
      name: "Sergio Esteban",
      shortName: "Sergio Esteban",
      slug: slugify("Sergio Esteban"),
      photo: null,
      position: PlayerPosition.FORWARD,
      shirtNumber: 45,
      age: 19,
      dateOfBirth: null,
      nationality: "Spain",
      countryOfBirth: null,
      heightCm: null,
      weightKg: null,
      preferredFoot: null,
      isActive: true,
      isInjured: false,
      isSuspended: false,
      injuryNote: null,
      marketValue: 100000,
      lastSyncedAt: new Date(),
    },
  ];

  for (const player of players) {
    await prisma.player.upsert({
      where: {
        teamId_name: {
          teamId: player.teamId,
          name: player.name,
        },
      },
      update: player,
      create: player,
    });
  }

  console.log(`✅ Atlético Madrid players seeded: ${players.length}`);
}

main()
  .catch((error) => {
    console.error("❌ Error seeding Atlético Madrid players:", error);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });