// prisma/seed-team-profiles.ts
import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const teamProfiles = [
  {
    teamId: "cmmx9iqvb0007hxghy2ko9t0x",
    fullName: "AFC Ajax",
    nickname: "De Godenzonen",
    city: "Amsterdam",
    country: "Netherlands",
    foundedYear: 1900,
    venueName: "Johan Cruyff Arena",
    description: "Один із найвідоміших клубів Нідерландів із сильною академією та атакувальним стилем гри.",
    externalSource: "manual-seed",
  },
  {
    teamId: "cmmx9iqyk0008hxgh842jjrrq",
    fullName: "FC Barcelona",
    nickname: "Barça",
    city: "Barcelona",
    country: "Spain",
    foundedYear: 1899,
    venueName: "Camp Nou",
    description: "Легендарний іспанський клуб із багатою історією, культовою академією La Masia та яскравою ігровою філософією.",
    externalSource: "manual-seed",
  },
  {
    teamId: "cmmx9ir090009hxghm372qe1q",
    fullName: "Liverpool FC",
    nickname: "The Reds",
    city: "Liverpool",
    country: "England",
    foundedYear: 1892,
    venueName: "Anfield",
    description: "Англійський гранд із легендарною атмосферою стадіону та великою єврокубковою історією.",
    externalSource: "manual-seed",
  },
  {
    teamId: "cmmx9ir1t000ahxghypdyfzra",
    fullName: "Club Atlético de Madrid",
    nickname: "Los Colchoneros",
    city: "Madrid",
    country: "Spain",
    foundedYear: 1903,
    venueName: "Metropolitano",
    description: "Один із провідних клубів Іспанії, відомий характером, інтенсивною грою та сильною обороною.",
    externalSource: "manual-seed",
  },
  {
    teamId: "cmmx9ir39000bhxghzo41n8cq",
    fullName: "FC Bayern München",
    nickname: "Bayern",
    city: "Munich",
    country: "Germany",
    foundedYear: 1900,
    venueName: "Allianz Arena",
    description: "Найтитулованіший клуб Німеччини, постійний претендент на трофеї в Європі.",
    externalSource: "manual-seed",
  },
  {
    teamId: "cmmx9ir4k000chxghj0rc05dg",
    fullName: "Manchester City FC",
    nickname: "City",
    city: "Manchester",
    country: "England",
    foundedYear: 1880,
    venueName: "Etihad Stadium",
    description: "Один із найсильніших клубів сучасної Англії з технічною та домінуючою грою.",
    externalSource: "manual-seed",
  },
  {
    teamId: "cmmx9ir67000dhxghvovmmf16",
    fullName: "Sport Lisboa e Benfica",
    nickname: "Benfica",
    city: "Lisbon",
    country: "Portugal",
    foundedYear: 1904,
    venueName: "Estádio da Luz",
    description: "Португальський гранд із великою фан-базою та сильними традиціями розвитку талантів.",
    externalSource: "manual-seed",
  },
  {
    teamId: "cmmx9ir81000ehxghdvjj8qao",
    fullName: "Eintracht Frankfurt",
    nickname: "Die Adler",
    city: "Frankfurt",
    country: "Germany",
    foundedYear: 1899,
    venueName: "Deutsche Bank Park",
    description: "Німецький клуб із бойовим характером та яскравою підтримкою трибун.",
    externalSource: "manual-seed",
  },
  {
    teamId: "cmmx9ir9s000fhxghvwedq0e3",
    fullName: "Newcastle United FC",
    nickname: "The Magpies",
    city: "Newcastle upon Tyne",
    country: "England",
    foundedYear: 1892,
    venueName: "St James' Park",
    description: "Клуб із великою історією, потужною підтримкою вболівальників та амбітним сучасним розвитком.",
    externalSource: "manual-seed",
  },
  {
    teamId: "cmmx9irif000ghxgh6d4k8bly",
    fullName: "FK Bodø/Glimt",
    nickname: "Glimt",
    city: "Bodø",
    country: "Norway",
    foundedYear: 1916,
    venueName: "Aspmyra Stadion",
    description: "Норвезький клуб, який став помітною силою завдяки сміливому й швидкому футболу.",
    externalSource: "manual-seed",
  },
  {
    teamId: "cmmx9irk5000hhxghn3cjtuul",
    fullName: "Olympiacos FC",
    nickname: "Thrylos",
    city: "Piraeus",
    country: "Greece",
    foundedYear: 1925,
    venueName: "Karaiskakis Stadium",
    description: "Найвідоміший клуб Греції з великою кількістю титулів та єврокубковим досвідом.",
    externalSource: "manual-seed",
  },
  {
    teamId: "cmmx9irlx000ihxghmeu58w4r",
    fullName: "Olympique de Marseille",
    nickname: "OM",
    city: "Marseille",
    country: "France",
    foundedYear: 1899,
    venueName: "Orange Vélodrome",
    description: "Французький клуб із харизматичною атмосферою та значною історією на європейській арені.",
    externalSource: "manual-seed",
  },
  {
    teamId: "cmmx9irnn000khxgh2bx95p67",
    fullName: "Chelsea FC",
    nickname: "The Blues",
    city: "London",
    country: "England",
    foundedYear: 1905,
    venueName: "Stamford Bridge",
    description: "Один із найпомітніших клубів Англії з багатою сучасною трофейною історією.",
    externalSource: "manual-seed",
  },
  {
    teamId: "cmmx9irn4000jhxghcejdqwdu",
    fullName: "Athletic Club",
    nickname: "Los Leones",
    city: "Bilbao",
    country: "Spain",
    foundedYear: 1898,
    venueName: "San Mamés",
    description: "Унікальний баскський клуб зі своєю ідентичністю та сильними традиціями.",
    externalSource: "manual-seed",
  },
  {
    teamId: "cmmx9irqv000mhxghaxm8i9t3",
    fullName: "Pafos FC",
    nickname: "Pafos",
    city: "Paphos",
    country: "Cyprus",
    foundedYear: 2014,
    venueName: "Pafiako Stadium",
    description: "Кіпрський клуб, який активно розвивається та набирає вагу на внутрішній і європейській арені.",
    externalSource: "manual-seed",
  },
  {
    teamId: "cmmx9irqh000lhxgh1p06udt0",
    fullName: "Galatasaray SK",
    nickname: "Cimbom",
    city: "Istanbul",
    country: "Turkey",
    foundedYear: 1905,
    venueName: "RAMS Park",
    description: "Один із найтитулованіших клубів Туреччини з шаленою атмосферою домашніх матчів.",
    externalSource: "manual-seed",
  },
  {
    teamId: "cmmx9irsj000ohxghy3rodg0o",
    fullName: "Paris Saint-Germain",
    nickname: "PSG",
    city: "Paris",
    country: "France",
    foundedYear: 1970,
    venueName: "Parc des Princes",
    description: "Французький топ-клуб із зірковим складом та амбіціями домінувати в Європі.",
    externalSource: "manual-seed",
  },
  {
    teamId: "cmmx9irsi000nhxghrx410emk",
    fullName: "Club Brugge KV",
    nickname: "Blauw-Zwart",
    city: "Bruges",
    country: "Belgium",
    foundedYear: 1891,
    venueName: "Jan Breydel Stadium",
    description: "Один із найсильніших бельгійських клубів із хорошою єврокубковою історією.",
    externalSource: "manual-seed",
  },
  {
    teamId: "cmmx9iru9000phxgh8j0m1a74",
    fullName: "FC Copenhagen",
    nickname: "FCK",
    city: "Copenhagen",
    country: "Denmark",
    foundedYear: 1992,
    venueName: "Parken Stadium",
    description: "Провідний клуб Данії, який регулярно виступає в єврокубках.",
    externalSource: "manual-seed",
  },
  {
    teamId: "cmmx9iru9000qhxgh9r6rjwb0",
    fullName: "AS Monaco",
    nickname: "Monaco",
    city: "Monaco",
    country: "Monaco",
    foundedYear: 1924,
    venueName: "Stade Louis II",
    description: "Клуб із відомою академією та сильними традиціями вирощування топ-гравців.",
    externalSource: "manual-seed",
  },
  {
    teamId: "cmmx9irvv000rhxgh0x4znsu5",
    fullName: "FC Internazionale Milano",
    nickname: "Inter",
    city: "Milan",
    country: "Italy",
    foundedYear: 1908,
    venueName: "San Siro",
    description: "Один із грандів італійського футболу з великою внутрішньою та міжнародною історією.",
    externalSource: "manual-seed",
  },
  {
    teamId: "cmmx9irw1000shxghi9rkx5xh",
    fullName: "PSV Eindhoven",
    nickname: "PSV",
    city: "Eindhoven",
    country: "Netherlands",
    foundedYear: 1913,
    venueName: "Philips Stadion",
    description: "Один із головних клубів Нідерландів із сильним акцентом на атаку та розвиток молоді.",
    externalSource: "manual-seed",
  },
  {
    teamId: "cmmx9irxx000uhxghov2dh7y5",
    fullName: "SK Slavia Praha",
    nickname: "Slavia",
    city: "Prague",
    country: "Czech Republic",
    foundedYear: 1892,
    venueName: "Fortuna Arena",
    description: "Один із провідних клубів Чехії, стабільний учасник єврокубків.",
    externalSource: "manual-seed",
  },
  {
    teamId: "cmmx9irxx000thxghs7g67ytr",
    fullName: "Real Madrid CF",
    nickname: "Los Blancos",
    city: "Madrid",
    country: "Spain",
    foundedYear: 1902,
    venueName: "Santiago Bernabéu",
    description: "Найуспішніший клуб Європи за кількістю великих міжнародних трофеїв.",
    externalSource: "manual-seed",
  },
  {
    teamId: "cmmx9irzk000vhxgh1ccm9fcc",
    fullName: "Qarabağ FK",
    nickname: "Qarabağ",
    city: "Baku",
    country: "Azerbaijan",
    foundedYear: 1987,
    venueName: "Azersun Arena",
    description: "Азербайджанський клуб, який регулярно представляє країну в єврокубках.",
    externalSource: "manual-seed",
  },
  {
    teamId: "cmmx9irzm000whxghl1er4o41",
    fullName: "Sporting Clube de Portugal",
    nickname: "Sporting",
    city: "Lisbon",
    country: "Portugal",
    foundedYear: 1906,
    venueName: "Estádio José Alvalade",
    description: "Великий португальський клуб із сильною академією та великим внеском у розвиток зірок.",
    externalSource: "manual-seed",
  },
  {
    teamId: "cmmx9is18000xhxghhjqv7i1d",
    fullName: "Juventus FC",
    nickname: "Juve",
    city: "Turin",
    country: "Italy",
    foundedYear: 1897,
    venueName: "Allianz Stadium",
    description: "Один із найуспішніших клубів Італії з великим внутрішнім домінуванням у різні періоди.",
    externalSource: "manual-seed",
  },
  {
    teamId: "cmmx9is1d000yhxghqr9lr4ve",
    fullName: "Arsenal FC",
    nickname: "The Gunners",
    city: "London",
    country: "England",
    foundedYear: 1886,
    venueName: "Emirates Stadium",
    description: "Лондонський топ-клуб із яскравим стилем гри та сильними сучасними амбіціями.",
    externalSource: "manual-seed",
  },
  {
    teamId: "cmmx9is390010hxghnh8jroup",
    fullName: "SSC Napoli",
    nickname: "Napoli",
    city: "Naples",
    country: "Italy",
    foundedYear: 1926,
    venueName: "Stadio Diego Armando Maradona",
    description: "Італійський клуб із пристрасною підтримкою та яскравим футбольним стилем.",
    externalSource: "manual-seed",
  },
  {
    teamId: "cmmx9is2w000zhxghcf6hpuu9",
    fullName: "Atalanta BC",
    nickname: "La Dea",
    city: "Bergamo",
    country: "Italy",
    foundedYear: 1907,
    venueName: "Gewiss Stadium",
    description: "Клуб, відомий сміливою атакувальною моделлю та сильним розвитком гравців.",
    externalSource: "manual-seed",
  },
  {
    teamId: "cmmx9is520011hxghwp94t1es",
    fullName: "FC Kairat",
    nickname: "Kairat",
    city: "Almaty",
    country: "Kazakhstan",
    foundedYear: 1954,
    venueName: "Central Stadium",
    description: "Один із найвідоміших клубів Казахстану з серйозними внутрішніми амбіціями.",
    externalSource: "manual-seed",
  },
  {
    teamId: "cmmx9is770012hxghqytqtvpq",
    fullName: "Tottenham Hotspur FC",
    nickname: "Spurs",
    city: "London",
    country: "England",
    foundedYear: 1882,
    venueName: "Tottenham Hotspur Stadium",
    description: "Англійський клуб із сучасною ареною, яскравою атакою та великою аудиторією вболівальників.",
    externalSource: "manual-seed",
  },
  {
    teamId: "cmmx9is830013hxgh82zrdov8",
    fullName: "Royale Union Saint-Gilloise",
    nickname: "Union SG",
    city: "Brussels",
    country: "Belgium",
    foundedYear: 1897,
    venueName: "Stade Joseph Marien",
    description: "Бельгійський клуб із історією та новою хвилею успіху в сучасному футболі.",
    externalSource: "manual-seed",
  },
  {
    teamId: "cmmx9is900014hxghqk1y3lzr",
    fullName: "Villarreal CF",
    nickname: "El Submarino Amarillo",
    city: "Villarreal",
    country: "Spain",
    foundedYear: 1923,
    venueName: "Estadio de la Cerámica",
    description: "Іспанський клуб, відомий стабільністю, розумною селекцією та єврокубковими успіхами.",
    externalSource: "manual-seed",
  },
  {
    teamId: "cmmx9isbh0015hxghnextdjya",
    fullName: "Borussia Dortmund",
    nickname: "BVB",
    city: "Dortmund",
    country: "Germany",
    foundedYear: 1909,
    venueName: "Signal Iduna Park",
    description: "Німецький гранд із легендарною жовто-чорною стіною та яскравим молодіжним футболом.",
    externalSource: "manual-seed",
  },
  {
    teamId: "cmmx9isde0016hxgh9195g1a3",
    fullName: "Bayer 04 Leverkusen",
    nickname: "Werkself",
    city: "Leverkusen",
    country: "Germany",
    foundedYear: 1904,
    venueName: "BayArena",
    description: "Німецький клуб із технічною грою та сильною сучасною структурою.",
    externalSource: "manual-seed",
  },
  {
    teamId: "cmn52uutm0001c355a9qppqv3",
    fullName: "Ukraine National Team",
    nickname: "Ukraine",
    city: "Kyiv",
    country: "Ukraine",
    foundedYear: 1992,
    venueName: "National Team Venues",
    description: "Національна збірна України з великою футбольною історією та сильним емоційним значенням для вболівальників.",
    externalSource: "manual-seed",
  },
  {
    teamId: "cmn52wce80002c355dosgfde3",
    fullName: "Sweden National Team",
    nickname: "Sweden",
    city: "Stockholm",
    country: "Sweden",
    foundedYear: 1904,
    venueName: "National Team Venues",
    description: "Національна збірна Швеції з традиціями, дисципліною та значною історією міжнародних виступів.",
    externalSource: "manual-seed",
  },
];

async function main() {
  console.log("🌱 Seeding team profiles...");

  for (const profile of teamProfiles) {
    await prisma.teamProfile.upsert({
      where: { teamId: profile.teamId },
      update: {
        fullName: profile.fullName,
        nickname: profile.nickname,
        city: profile.city,
        country: profile.country,
        foundedYear: profile.foundedYear,
        venueName: profile.venueName,
        description: profile.description,
        externalSource: profile.externalSource,
        externalUpdatedAt: new Date(),
      },
      create: {
        teamId: profile.teamId,
        fullName: profile.fullName,
        nickname: profile.nickname,
        city: profile.city,
        country: profile.country,
        foundedYear: profile.foundedYear,
        venueName: profile.venueName,
        description: profile.description,
        externalSource: profile.externalSource,
        externalUpdatedAt: new Date(),
      },
    });
  }

  console.log(`✅ Seeded ${teamProfiles.length} team profiles`);
}

main()
  .catch((error) => {
    console.error("❌ Seed failed:");
    console.error(error);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });